language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '8'
  - '6'

before_install:
  - npm i -g npm@5.3.0

install:
  - npm install

script:
  - npm test

before_deploy:
  - npm run build-bin

deploy:
  - provider: releases
    api-key: "$GITHUB_RELEASE_TOKEN"
    file:
      - "dist-bin/*"
    skip_cleanup: true
    file_glob: true
    on:
      repo: SkygearIO/skycli
      tags: true
      node_js: 8
