version: '3'

services:
  app:
    image: node:8
    volumes:
      - user_data:/root/.skycli
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

volumes:
  user_data:
    driver: local
